{% set name = "simhash-py" %}
{% set version = "0.4.0" %}
{% set sha256 = "c83e20cfac873ba9067c564135c293db635cbd7372f126e9bcfb0fabf9fd0234" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 1002
  skip: True  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython <3
    - pip
  run:
    - python
    - six

test:
  imports:
    - simhash

about:
  home: http://github.com/seomoz/simhash-py/
  license: MIT
  license_family: MIT
  # the licence file was excluded from PyPi's .tar.gz in v0.4.0 by accident
  # but it will be included in the following releases
  # license_file: LICENSE
  summary: 'Simhash and near-duplicate detection'
  description: |
     This library enables the efficient identification of
     near-duplicate documents using simhash using a C++ extension.
  doc_url: https://github.com/seomoz/simhash-py
  dev_url: https://github.com/seomoz/simhash-py

extra:
  recipe-maintainers:
    - rth
