# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxpython2.7
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxpython3.6
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxpython3.7
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxpython2.7
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxpython3.6
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxpython3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "LGedlrz0Fc2/m27WS1GkrmjCSNBwM5ZIoYbkWKxdDzYmOQPWs2txog16trBcWWOey+NoCFkC5BY9SPWlZXWZ1nglrZEzESA/G0r1dGhVeT/VBqFDeOZpMVQWNbnMvPuyZEyhS94+ca71nNQawJjmxXYA06mwiILuxrK0SJFITs/eu8eq4xsqDAkgtgfQNewdm8+dCkGMZAeyUKlEJvXvitbmUafme3J1L0xTP6FDXdHTK3gahNRj3di5nqLFpk3AowYsJJVq+mBpFgkwSwIG5qjWTMCBanMXwYsts9eV24wGNIcnRbGIFmVC0nUedSIXZxh8kvTgmffWN78BGaCZOUNAKkWkjIVNNY0FY61XMHp3rvZOp4lhTMJJfkrx0hRZzSI0os10be4YD9Y+y6/uHdSWxN2kLx8gkEKkMaCqUMTwVbHhpeGoSXzVDoiL9neqC7+6uY1PdFwzn+gbuwKs9Bf8eNJrRSo0l8zvneHumTNfIbwT+vrfjbYO3zIhlo6fitWgEenjX5B6QZvizNF+m7koxKRf/2Ykz/i+HebmFGzH2oimJNnVnF97oCDCZpufD7ZygKDnXpbWXqMOzTrr5Gh5lGfc0A47NIEWB2dSxWtf/ixy/Zef791PAxoAPv1Mlwqfs+R0oYDIba6FBEPrgzT9kGF/QoGGJwq7AHOIJSY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
