travis:
  secure:
    BINSTAR_TOKEN: LGedlrz0Fc2/m27WS1GkrmjCSNBwM5ZIoYbkWKxdDzYmOQPWs2txog16trBcWWOey+NoCFkC5BY9SPWlZXWZ1nglrZEzESA/G0r1dGhVeT/VBqFDeOZpMVQWNbnMvPuyZEyhS94+ca71nNQawJjmxXYA06mwiILuxrK0SJFITs/eu8eq4xsqDAkgtgfQNewdm8+dCkGMZAeyUKlEJvXvitbmUafme3J1L0xTP6FDXdHTK3gahNRj3di5nqLFpk3AowYsJJVq+mBpFgkwSwIG5qjWTMCBanMXwYsts9eV24wGNIcnRbGIFmVC0nUedSIXZxh8kvTgmffWN78BGaCZOUNAKkWkjIVNNY0FY61XMHp3rvZOp4lhTMJJfkrx0hRZzSI0os10be4YD9Y+y6/uHdSWxN2kLx8gkEKkMaCqUMTwVbHhpeGoSXzVDoiL9neqC7+6uY1PdFwzn+gbuwKs9Bf8eNJrRSo0l8zvneHumTNfIbwT+vrfjbYO3zIhlo6fitWgEenjX5B6QZvizNF+m7koxKRf/2Ykz/i+HebmFGzH2oimJNnVnF97oCDCZpufD7ZygKDnXpbWXqMOzTrr5Gh5lGfc0A47NIEWB2dSxWtf/ixy/Zef791PAxoAPv1Mlwqfs+R0oYDIba6FBEPrgzT9kGF/QoGGJwq7AHOIJSY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
