travis:
  secure:
    BINSTAR_TOKEN: RhYvxyRbB7Yj7zULJbbid3jbw0CUtc/vx42/mT9dLm3luDoDyLfp7bAng8AZ/QoprSNePcsDrt1Vl18jLsk3oDySLqnk+PrP+RT6SRXYC20dZLjo3RwlM5ObQYM6LqN4AglAJOx8BTo74PF45cGdVmogjSL1CrhAYA3lQXR3/S43DhhUlZ4V7zRHU4DsUkmfAMu8sNaf8wQEdlfQV32T72sU/sn5wAcAb9hI2gXXtPGU0MeR54PPU3Tig9KqdSo40/w+R4vrjZT7qyzi0Hp3307ZLnlJZku5PCnjNJgbhX6DsIPJgWT8qr+QQrNWs/vQdcr9N3yodxmFTCQpOfb9/PndvCGFIsp3dnyUahBmSyizTx9xlKRiOIrfNjtIPKjrujIq5kBhd1YLM8vXT7X1vxKtrEAYPL+gz5nNpEVytTBHkpEskps0zJRA5+7Iqadltc0HS0QiH99kdv30bi9vlVfUuHGqeFZllC1M0BLtT6+wkU0zNNXBdB+XVy//pUek8NVDiTO72uo8j3l7DyS0I0YKsIvEiTBNGcP8XPCP4QDdpdZc8tT+R9Xqvj2f4g2mxkStpr610nx3HoLJ55Nl3k/MpOys1Mn/KWDFTJFNV1blrFbAgMdZJIKMKlC/2XYMRaam+ra9xUGzASXyUpN+iPg2faUG3zBgn7VgzfhB8a0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
